CommitMsg:
  ALL:
    on_warn: fail
PreCommit:
  ALL:
    on_warn: fail
  BundleAudit:
    enabled: true
    command: ['bundle-audit', '--ignore', 'CVE-2015-9284']
  BundleCheck:
    enabled: true
  BundleOutdated:
    enabled: true
  EsLint:
    enabled: true
    required_executable: './node_modules/.bin/eslint'
    include: 'app/javascript/**/*.js'
  Fasterer:
    enabled: true
  Flay:
    enabled: true
  JsonSyntax:
    enabled: true
  RailsBestPractices:
    enabled: true
    command: ['rails_best_practices', 'app', '--spec']
    flags: ['-c', '.rails_best_practices.yml']
  Reek:
    enabled: true
  RuboCop:
    enabled: true
  SlimLint:
    enabled: true
  Stylelint:
    enabled: true
    required_executable: './node_modules/.bin/stylelint'
    include: 'app/javascript/stylesheets/**/*.scss'
  YamlSyntax:
    enabled: true
PrePush:
  Brakeman:
    enabled: true