require: rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'config/initializers/*'
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'lib/tasks/auto_annotate_models.rake'
  IgnoredMethods:
    - 'describe'
    - 'context'
    - 'shared_examples'
    - 'draw'
    - 'define'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
Style/MixinUsage:
  Exclude:
    - 'db/seeds.rb'
