require: rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'lib/tasks/auto_annotate_models.rake'
  ExcludedMethods:
    - 'describe'
    - 'shared_examples'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
Style/MixinUsage:
  Exclude:
    - 'db/seeds.rb'
Lint/EmptyFile:
  Exclude:
    - 'config/initializers/*'